---
- name: Create Virtual Machine Scale Set using user image
  hosts: localhost
  vars:
    rgName: azhuzhi-custom-vmss1
    location: southcentralus
  tasks:
    - name: Create resource group
      azure_rm_resourcegroup:
        name: "{{ rgName }}"
        location: "{{ location }}"
    - name: Create Ubuntu Virtual Machine from custom image
      register: armOutput
      azure_rm_deployment:
        state: present
        location: "{{ location }}"
        resource_group_name: "{{ rgName }}"
        deployment_mode: incremental
        template: "{{ lookup('file','vmsspublic.json') }}"
        parameters: "{{ (lookup('file','vmsspublic.parameters.json') | from_json).parameters }}"
    - name: get Azure Resource Manager Template output
      debug:
        msg: "{{ armOutput }}"